repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: make
        args: ["isort-check"]
        language: system
        pass_filenames: false
      - id: black
        name: black
        entry: make
        args: ["black-check"]
        language: system
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: make
        args: ["flake8"]
        language: system
        pass_filenames: false
